project_id = "xvpqgwbktpfodbuhwqhh"

[functions.event-bus]
verify_jwt = false

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[edge-runtime]
enabled = true
port = 54329

[functions.analyze-swot]
verify_jwt = false

[functions.generate-post-image]
verify_jwt = false

[functions.generate-content-with-ai]
verify_jwt = false

[functions.cnpj-lookup]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.signup]
verify_jwt = false

[functions.generate-contract-clauses]
verify_jwt = false

[functions.event-bus]
verify_jwt = false

[functions.generate-task-briefing]
verify_jwt = false

[functions.generate-reflexao]
verify_jwt = false

[functions.gerar-insights-diarios]
verify_jwt = false

[functions.avaliar-meta-smart]
verify_jwt = false

[functions.prever-horarios-foco]
verify_jwt = false

[functions.generate-roteiro-audiovisual]
verify_jwt = false
